FEATURES_PATH='../../../../data/building_damage/features'
EXPERIMENTS_PATH='../../../../data-old/building_damage/experiments'
PREDICTIONS_PATH='../../../../data-old/building_damage/predictions'
MODELS_PATH='../../../../data-old/building_damage/models'
RASTERS_PATH='../../../../data/building_damage/city_rasters'
ANNOTATIONS_PATH='../../../../data/building_damage/annotations'
POLYGONS_PATH='../../../../data/building_damage/polygons'
